#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatsApp_Robot
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="uMarketing")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcliente(cliente instance);
    partial void Updatecliente(cliente instance);
    partial void Deletecliente(cliente instance);
    partial void Insertgrupo(grupo instance);
    partial void Updategrupo(grupo instance);
    partial void Deletegrupo(grupo instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::WhatsApp_Robot.Properties.Settings.Default.uMarketingConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<cliente> clientes
		{
			get
			{
				return this.GetTable<cliente>();
			}
		}
		
		public System.Data.Linq.Table<grupo> grupos
		{
			get
			{
				return this.GetTable<grupo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cliente")]
	public partial class cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Cliente_ID;
		
		private string _ClienteNome;
		
		private string _Telefone;
		
		private string _Email;
		
		private string _Endereco;
		
		private System.Nullable<int> _GRUPO_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCliente_IDChanging(int value);
    partial void OnCliente_IDChanged();
    partial void OnClienteNomeChanging(string value);
    partial void OnClienteNomeChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnEnderecoChanging(string value);
    partial void OnEnderecoChanged();
    partial void OnGRUPO_IDChanging(System.Nullable<int> value);
    partial void OnGRUPO_IDChanged();
    #endregion
		
		public cliente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cliente_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Cliente_ID
		{
			get
			{
				return this._Cliente_ID;
			}
			set
			{
				if ((this._Cliente_ID != value))
				{
					this.OnCliente_IDChanging(value);
					this.SendPropertyChanging();
					this._Cliente_ID = value;
					this.SendPropertyChanged("Cliente_ID");
					this.OnCliente_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClienteNome", DbType="NVarChar(200)")]
		public string ClienteNome
		{
			get
			{
				return this._ClienteNome;
			}
			set
			{
				if ((this._ClienteNome != value))
				{
					this.OnClienteNomeChanging(value);
					this.SendPropertyChanging();
					this._ClienteNome = value;
					this.SendPropertyChanged("ClienteNome");
					this.OnClienteNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone", DbType="NVarChar(200)")]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Endereco", DbType="NVarChar(MAX)")]
		public string Endereco
		{
			get
			{
				return this._Endereco;
			}
			set
			{
				if ((this._Endereco != value))
				{
					this.OnEnderecoChanging(value);
					this.SendPropertyChanging();
					this._Endereco = value;
					this.SendPropertyChanged("Endereco");
					this.OnEnderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPO_ID", DbType="Int")]
		public System.Nullable<int> GRUPO_ID
		{
			get
			{
				return this._GRUPO_ID;
			}
			set
			{
				if ((this._GRUPO_ID != value))
				{
					this.OnGRUPO_IDChanging(value);
					this.SendPropertyChanging();
					this._GRUPO_ID = value;
					this.SendPropertyChanged("GRUPO_ID");
					this.OnGRUPO_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.grupo")]
	public partial class grupo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GRUPO_ID;
		
		private string _GRUPO_NAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGRUPO_IDChanging(int value);
    partial void OnGRUPO_IDChanged();
    partial void OnGRUPO_NOMEChanging(string value);
    partial void OnGRUPO_NOMEChanged();
    #endregion
		
		public grupo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPO_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int GRUPO_ID
		{
			get
			{
				return this._GRUPO_ID;
			}
			set
			{
				if ((this._GRUPO_ID != value))
				{
					this.OnGRUPO_IDChanging(value);
					this.SendPropertyChanging();
					this._GRUPO_ID = value;
					this.SendPropertyChanged("GRUPO_ID");
					this.OnGRUPO_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="GRUPO_NAME", Storage="_GRUPO_NAME", DbType="NVarChar(200)")]
		public string GRUPO_NOME
		{
			get
			{
				return this._GRUPO_NAME;
			}
			set
			{
				if ((this._GRUPO_NAME != value))
				{
					this.OnGRUPO_NOMEChanging(value);
					this.SendPropertyChanging();
					this._GRUPO_NAME = value;
					this.SendPropertyChanged("GRUPO_NOME");
					this.OnGRUPO_NOMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
