
namespace WhatsApp_Robot
{
    partial class frmCustomer
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmCustomer));
            this.errorProvider = new System.Windows.Forms.ErrorProvider(this.components);
            this.bunifuSnackbar = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.txtTlfSufixo = new Bunifu.UI.WinForms.BunifuDropdown();
            this.txtTelefone = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtClienteName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtClienteID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtEndereco = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.cmbGrupo = new Bunifu.UI.WinForms.BunifuDropdown();
            this.btnEyeNo = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSubmit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnAlter = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnRefresh = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuSeparator1 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider)).BeginInit();
            this.SuspendLayout();
            // 
            // errorProvider
            // 
            this.errorProvider.ContainerControl = this;
            this.errorProvider.Icon = ((System.Drawing.Icon)(resources.GetObject("errorProvider.Icon")));
            // 
            // bunifuSnackbar
            // 
            this.bunifuSnackbar.AllowDragging = false;
            this.bunifuSnackbar.AllowMultipleViews = true;
            this.bunifuSnackbar.ClickToClose = true;
            this.bunifuSnackbar.DoubleClickToClose = true;
            this.bunifuSnackbar.DurationAfterIdle = 3000;
            this.bunifuSnackbar.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bunifuSnackbar.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.bunifuSnackbar.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar.FadeCloseIcon = false;
            this.bunifuSnackbar.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bunifuSnackbar.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.bunifuSnackbar.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar.Margin = 10;
            this.bunifuSnackbar.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar.MaximumViews = 7;
            this.bunifuSnackbar.MessageRightMargin = 15;
            this.bunifuSnackbar.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar.ShowBorders = false;
            this.bunifuSnackbar.ShowCloseIcon = true;
            this.bunifuSnackbar.ShowIcon = true;
            this.bunifuSnackbar.ShowShadows = true;
            this.bunifuSnackbar.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.bunifuSnackbar.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar.ViewsMargin = 7;
            this.bunifuSnackbar.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.bunifuSnackbar.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar.ZoomCloseIcon = true;
            // 
            // txtTlfSufixo
            // 
            this.txtTlfSufixo.BackColor = System.Drawing.Color.Transparent;
            this.txtTlfSufixo.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.txtTlfSufixo.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.txtTlfSufixo.BorderRadius = 5;
            this.txtTlfSufixo.Color = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.txtTlfSufixo.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.txtTlfSufixo.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.txtTlfSufixo.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTlfSufixo.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.txtTlfSufixo.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.txtTlfSufixo.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.txtTlfSufixo.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.txtTlfSufixo.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.txtTlfSufixo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.txtTlfSufixo.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.txtTlfSufixo.FillDropDown = true;
            this.txtTlfSufixo.FillIndicator = false;
            this.txtTlfSufixo.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.txtTlfSufixo.Font = new System.Drawing.Font("Rubik", 8F);
            this.txtTlfSufixo.ForeColor = System.Drawing.Color.White;
            this.txtTlfSufixo.FormattingEnabled = true;
            this.txtTlfSufixo.Icon = null;
            this.txtTlfSufixo.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.txtTlfSufixo.IndicatorColor = System.Drawing.Color.White;
            this.txtTlfSufixo.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.txtTlfSufixo.ItemBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.txtTlfSufixo.ItemBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.txtTlfSufixo.ItemForeColor = System.Drawing.Color.White;
            this.txtTlfSufixo.ItemHeight = 26;
            this.txtTlfSufixo.ItemHighLightColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(220)))), ((int)(((byte)(161)))));
            this.txtTlfSufixo.ItemHighLightForeColor = System.Drawing.Color.White;
            this.txtTlfSufixo.Items.AddRange(new object[] {
            "+244",
            "+244",
            "+244",
            "+244",
            "+244"});
            this.txtTlfSufixo.ItemTopMargin = 3;
            this.txtTlfSufixo.Location = new System.Drawing.Point(37, 122);
            this.txtTlfSufixo.Name = "txtTlfSufixo";
            this.txtTlfSufixo.Size = new System.Drawing.Size(77, 32);
            this.txtTlfSufixo.TabIndex = 63;
            this.txtTlfSufixo.Text = null;
            this.txtTlfSufixo.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.txtTlfSufixo.TextLeftMargin = 5;
            // 
            // txtTelefone
            // 
            this.txtTelefone.AcceptsReturn = false;
            this.txtTelefone.AcceptsTab = false;
            this.txtTelefone.AnimationSpeed = 200;
            this.txtTelefone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTelefone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTelefone.BackColor = System.Drawing.Color.Transparent;
            this.txtTelefone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTelefone.BackgroundImage")));
            this.txtTelefone.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(255)))), ((int)(((byte)(175)))));
            this.txtTelefone.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTelefone.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(219)))), ((int)(((byte)(165)))));
            this.txtTelefone.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.txtTelefone.BorderRadius = 10;
            this.txtTelefone.BorderThickness = 1;
            this.txtTelefone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTelefone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefone.DefaultFont = new System.Drawing.Font("Rubik", 8.9F);
            this.txtTelefone.DefaultText = "";
            this.txtTelefone.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.txtTelefone.ForeColor = System.Drawing.Color.White;
            this.txtTelefone.HideSelection = true;
            this.txtTelefone.IconLeft = null;
            this.txtTelefone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefone.IconPadding = 10;
            this.txtTelefone.IconRight = null;
            this.txtTelefone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefone.Lines = new string[0];
            this.txtTelefone.Location = new System.Drawing.Point(120, 121);
            this.txtTelefone.MaxLength = 32767;
            this.txtTelefone.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTelefone.Modified = false;
            this.txtTelefone.Multiline = false;
            this.txtTelefone.Name = "txtTelefone";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(255)))), ((int)(((byte)(175)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefone.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTelefone.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(219)))), ((int)(((byte)(165)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefone.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            stateProperties20.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            stateProperties20.ForeColor = System.Drawing.Color.White;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefone.OnIdleState = stateProperties20;
            this.txtTelefone.Padding = new System.Windows.Forms.Padding(3);
            this.txtTelefone.PasswordChar = '\0';
            this.txtTelefone.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTelefone.PlaceholderText = "Telefone";
            this.txtTelefone.ReadOnly = false;
            this.txtTelefone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTelefone.SelectedText = "";
            this.txtTelefone.SelectionLength = 0;
            this.txtTelefone.SelectionStart = 0;
            this.txtTelefone.ShortcutsEnabled = true;
            this.txtTelefone.Size = new System.Drawing.Size(200, 34);
            this.txtTelefone.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTelefone.TabIndex = 64;
            this.txtTelefone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTelefone.TextMarginBottom = 0;
            this.txtTelefone.TextMarginLeft = 3;
            this.txtTelefone.TextMarginTop = 0;
            this.txtTelefone.TextPlaceholder = "Telefone";
            this.txtTelefone.UseSystemPasswordChar = false;
            this.txtTelefone.WordWrap = true;
            // 
            // txtClienteName
            // 
            this.txtClienteName.AcceptsReturn = false;
            this.txtClienteName.AcceptsTab = false;
            this.txtClienteName.AnimationSpeed = 200;
            this.txtClienteName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtClienteName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtClienteName.BackColor = System.Drawing.Color.Transparent;
            this.txtClienteName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtClienteName.BackgroundImage")));
            this.txtClienteName.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(255)))), ((int)(((byte)(175)))));
            this.txtClienteName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtClienteName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(219)))), ((int)(((byte)(165)))));
            this.txtClienteName.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.txtClienteName.BorderRadius = 10;
            this.txtClienteName.BorderThickness = 1;
            this.txtClienteName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtClienteName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtClienteName.DefaultFont = new System.Drawing.Font("Rubik", 8.9F);
            this.txtClienteName.DefaultText = "";
            this.txtClienteName.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.txtClienteName.ForeColor = System.Drawing.Color.White;
            this.txtClienteName.HideSelection = true;
            this.txtClienteName.IconLeft = null;
            this.txtClienteName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtClienteName.IconPadding = 10;
            this.txtClienteName.IconRight = null;
            this.txtClienteName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtClienteName.Lines = new string[0];
            this.txtClienteName.Location = new System.Drawing.Point(37, 79);
            this.txtClienteName.MaxLength = 32767;
            this.txtClienteName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtClienteName.Modified = false;
            this.txtClienteName.Multiline = false;
            this.txtClienteName.Name = "txtClienteName";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(255)))), ((int)(((byte)(175)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtClienteName.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtClienteName.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(219)))), ((int)(((byte)(165)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtClienteName.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            stateProperties16.ForeColor = System.Drawing.Color.White;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtClienteName.OnIdleState = stateProperties16;
            this.txtClienteName.Padding = new System.Windows.Forms.Padding(3);
            this.txtClienteName.PasswordChar = '\0';
            this.txtClienteName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtClienteName.PlaceholderText = "Nome do cliente";
            this.txtClienteName.ReadOnly = false;
            this.txtClienteName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtClienteName.SelectedText = "";
            this.txtClienteName.SelectionLength = 0;
            this.txtClienteName.SelectionStart = 0;
            this.txtClienteName.ShortcutsEnabled = true;
            this.txtClienteName.Size = new System.Drawing.Size(283, 34);
            this.txtClienteName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtClienteName.TabIndex = 65;
            this.txtClienteName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtClienteName.TextMarginBottom = 0;
            this.txtClienteName.TextMarginLeft = 3;
            this.txtClienteName.TextMarginTop = 0;
            this.txtClienteName.TextPlaceholder = "Nome do cliente";
            this.txtClienteName.UseSystemPasswordChar = false;
            this.txtClienteName.WordWrap = true;
            // 
            // txtEmail
            // 
            this.txtEmail.AcceptsReturn = false;
            this.txtEmail.AcceptsTab = false;
            this.txtEmail.AnimationSpeed = 200;
            this.txtEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmail.BackColor = System.Drawing.Color.Transparent;
            this.txtEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmail.BackgroundImage")));
            this.txtEmail.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(255)))), ((int)(((byte)(175)))));
            this.txtEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(219)))), ((int)(((byte)(165)))));
            this.txtEmail.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.txtEmail.BorderRadius = 10;
            this.txtEmail.BorderThickness = 1;
            this.txtEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.DefaultFont = new System.Drawing.Font("Rubik", 8.9F);
            this.txtEmail.DefaultText = "";
            this.txtEmail.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.txtEmail.ForeColor = System.Drawing.Color.White;
            this.txtEmail.HideSelection = true;
            this.txtEmail.IconLeft = null;
            this.txtEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.IconPadding = 10;
            this.txtEmail.IconRight = null;
            this.txtEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.Lines = new string[0];
            this.txtEmail.Location = new System.Drawing.Point(37, 165);
            this.txtEmail.MaxLength = 32767;
            this.txtEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEmail.Modified = false;
            this.txtEmail.Multiline = false;
            this.txtEmail.Name = "txtEmail";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(255)))), ((int)(((byte)(175)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEmail.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(219)))), ((int)(((byte)(165)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            stateProperties12.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            stateProperties12.ForeColor = System.Drawing.Color.White;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnIdleState = stateProperties12;
            this.txtEmail.Padding = new System.Windows.Forms.Padding(3);
            this.txtEmail.PasswordChar = '\0';
            this.txtEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtEmail.PlaceholderText = "Email";
            this.txtEmail.ReadOnly = false;
            this.txtEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmail.SelectedText = "";
            this.txtEmail.SelectionLength = 0;
            this.txtEmail.SelectionStart = 0;
            this.txtEmail.ShortcutsEnabled = true;
            this.txtEmail.Size = new System.Drawing.Size(283, 34);
            this.txtEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtEmail.TabIndex = 66;
            this.txtEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtEmail.TextMarginBottom = 0;
            this.txtEmail.TextMarginLeft = 3;
            this.txtEmail.TextMarginTop = 0;
            this.txtEmail.TextPlaceholder = "Email";
            this.txtEmail.UseSystemPasswordChar = false;
            this.txtEmail.WordWrap = true;
            // 
            // txtClienteID
            // 
            this.txtClienteID.AcceptsReturn = false;
            this.txtClienteID.AcceptsTab = false;
            this.txtClienteID.AnimationSpeed = 200;
            this.txtClienteID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtClienteID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtClienteID.BackColor = System.Drawing.Color.Transparent;
            this.txtClienteID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtClienteID.BackgroundImage")));
            this.txtClienteID.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(255)))), ((int)(((byte)(175)))));
            this.txtClienteID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtClienteID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(219)))), ((int)(((byte)(165)))));
            this.txtClienteID.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.txtClienteID.BorderRadius = 10;
            this.txtClienteID.BorderThickness = 1;
            this.txtClienteID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtClienteID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtClienteID.DefaultFont = new System.Drawing.Font("Rubik", 8.9F);
            this.txtClienteID.DefaultText = "";
            this.txtClienteID.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.txtClienteID.ForeColor = System.Drawing.Color.White;
            this.txtClienteID.HideSelection = true;
            this.txtClienteID.IconLeft = null;
            this.txtClienteID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtClienteID.IconPadding = 10;
            this.txtClienteID.IconRight = null;
            this.txtClienteID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtClienteID.Lines = new string[0];
            this.txtClienteID.Location = new System.Drawing.Point(326, 79);
            this.txtClienteID.MaxLength = 32767;
            this.txtClienteID.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtClienteID.Modified = false;
            this.txtClienteID.Multiline = false;
            this.txtClienteID.Name = "txtClienteID";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(255)))), ((int)(((byte)(175)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtClienteID.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtClienteID.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(219)))), ((int)(((byte)(165)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtClienteID.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            stateProperties8.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            stateProperties8.ForeColor = System.Drawing.Color.White;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtClienteID.OnIdleState = stateProperties8;
            this.txtClienteID.Padding = new System.Windows.Forms.Padding(3);
            this.txtClienteID.PasswordChar = '\0';
            this.txtClienteID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtClienteID.PlaceholderText = "";
            this.txtClienteID.ReadOnly = false;
            this.txtClienteID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtClienteID.SelectedText = "";
            this.txtClienteID.SelectionLength = 0;
            this.txtClienteID.SelectionStart = 0;
            this.txtClienteID.ShortcutsEnabled = true;
            this.txtClienteID.Size = new System.Drawing.Size(32, 34);
            this.txtClienteID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtClienteID.TabIndex = 67;
            this.txtClienteID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtClienteID.TextMarginBottom = 0;
            this.txtClienteID.TextMarginLeft = 3;
            this.txtClienteID.TextMarginTop = 0;
            this.txtClienteID.TextPlaceholder = "";
            this.txtClienteID.UseSystemPasswordChar = false;
            this.txtClienteID.Visible = false;
            this.txtClienteID.WordWrap = true;
            // 
            // txtEndereco
            // 
            this.txtEndereco.AcceptsReturn = false;
            this.txtEndereco.AcceptsTab = false;
            this.txtEndereco.AnimationSpeed = 200;
            this.txtEndereco.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEndereco.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEndereco.BackColor = System.Drawing.Color.Transparent;
            this.txtEndereco.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEndereco.BackgroundImage")));
            this.txtEndereco.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(255)))), ((int)(((byte)(175)))));
            this.txtEndereco.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEndereco.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(219)))), ((int)(((byte)(165)))));
            this.txtEndereco.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.txtEndereco.BorderRadius = 10;
            this.txtEndereco.BorderThickness = 1;
            this.txtEndereco.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEndereco.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEndereco.DefaultFont = new System.Drawing.Font("Rubik", 8.9F);
            this.txtEndereco.DefaultText = "";
            this.txtEndereco.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.txtEndereco.ForeColor = System.Drawing.Color.White;
            this.txtEndereco.HideSelection = true;
            this.txtEndereco.IconLeft = null;
            this.txtEndereco.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEndereco.IconPadding = 10;
            this.txtEndereco.IconRight = null;
            this.txtEndereco.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEndereco.Lines = new string[0];
            this.txtEndereco.Location = new System.Drawing.Point(37, 211);
            this.txtEndereco.MaxLength = 32767;
            this.txtEndereco.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEndereco.Modified = false;
            this.txtEndereco.Multiline = true;
            this.txtEndereco.Name = "txtEndereco";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(255)))), ((int)(((byte)(175)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEndereco.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEndereco.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(219)))), ((int)(((byte)(165)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEndereco.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            stateProperties4.ForeColor = System.Drawing.Color.White;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEndereco.OnIdleState = stateProperties4;
            this.txtEndereco.Padding = new System.Windows.Forms.Padding(3);
            this.txtEndereco.PasswordChar = '\0';
            this.txtEndereco.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtEndereco.PlaceholderText = "Email";
            this.txtEndereco.ReadOnly = false;
            this.txtEndereco.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.txtEndereco.SelectedText = "";
            this.txtEndereco.SelectionLength = 0;
            this.txtEndereco.SelectionStart = 0;
            this.txtEndereco.ShortcutsEnabled = true;
            this.txtEndereco.Size = new System.Drawing.Size(283, 71);
            this.txtEndereco.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtEndereco.TabIndex = 68;
            this.txtEndereco.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtEndereco.TextMarginBottom = 0;
            this.txtEndereco.TextMarginLeft = 3;
            this.txtEndereco.TextMarginTop = 0;
            this.txtEndereco.TextPlaceholder = "Email";
            this.txtEndereco.UseSystemPasswordChar = false;
            this.txtEndereco.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Rubik Light", 10F);
            this.bunifuLabel3.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel3.Location = new System.Drawing.Point(50, 291);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(37, 16);
            this.bunifuLabel3.TabIndex = 69;
            this.bunifuLabel3.Text = "Grupo";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // cmbGrupo
            // 
            this.cmbGrupo.BackColor = System.Drawing.Color.Transparent;
            this.cmbGrupo.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.cmbGrupo.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.cmbGrupo.BorderRadius = 5;
            this.cmbGrupo.Color = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.cmbGrupo.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbGrupo.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbGrupo.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbGrupo.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbGrupo.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbGrupo.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbGrupo.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbGrupo.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbGrupo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbGrupo.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbGrupo.FillDropDown = true;
            this.cmbGrupo.FillIndicator = false;
            this.cmbGrupo.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbGrupo.Font = new System.Drawing.Font("Rubik", 8F);
            this.cmbGrupo.ForeColor = System.Drawing.Color.White;
            this.cmbGrupo.FormattingEnabled = true;
            this.cmbGrupo.Icon = null;
            this.cmbGrupo.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbGrupo.IndicatorColor = System.Drawing.Color.White;
            this.cmbGrupo.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbGrupo.ItemBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.cmbGrupo.ItemBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.cmbGrupo.ItemForeColor = System.Drawing.Color.White;
            this.cmbGrupo.ItemHeight = 26;
            this.cmbGrupo.ItemHighLightColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(220)))), ((int)(((byte)(161)))));
            this.cmbGrupo.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cmbGrupo.Items.AddRange(new object[] {
            "+244",
            "+244",
            "+244",
            "+244",
            "+244"});
            this.cmbGrupo.ItemTopMargin = 3;
            this.cmbGrupo.Location = new System.Drawing.Point(37, 311);
            this.cmbGrupo.Name = "cmbGrupo";
            this.cmbGrupo.Size = new System.Drawing.Size(283, 32);
            this.cmbGrupo.TabIndex = 70;
            this.cmbGrupo.Text = null;
            this.cmbGrupo.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbGrupo.TextLeftMargin = 5;
            // 
            // btnEyeNo
            // 
            this.btnEyeNo.AllowAnimations = true;
            this.btnEyeNo.AllowMouseEffects = true;
            this.btnEyeNo.AllowToggling = false;
            this.btnEyeNo.AnimationSpeed = 200;
            this.btnEyeNo.AutoGenerateColors = false;
            this.btnEyeNo.AutoRoundBorders = false;
            this.btnEyeNo.AutoSizeLeftIcon = true;
            this.btnEyeNo.AutoSizeRightIcon = true;
            this.btnEyeNo.BackColor = System.Drawing.Color.Transparent;
            this.btnEyeNo.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.btnEyeNo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEyeNo.BackgroundImage")));
            this.btnEyeNo.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEyeNo.ButtonText = "Plus-Circle";
            this.btnEyeNo.ButtonTextMarginLeft = 0;
            this.btnEyeNo.ColorContrastOnClick = 45;
            this.btnEyeNo.ColorContrastOnHover = 45;
            this.btnEyeNo.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnEyeNo.CustomizableEdges = borderEdges4;
            this.btnEyeNo.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEyeNo.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEyeNo.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEyeNo.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEyeNo.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnEyeNo.Font = new System.Drawing.Font("Font Awesome 5 Pro Solid", 12F);
            this.btnEyeNo.ForeColor = System.Drawing.Color.White;
            this.btnEyeNo.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEyeNo.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEyeNo.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEyeNo.IconMarginLeft = 11;
            this.btnEyeNo.IconPadding = 10;
            this.btnEyeNo.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEyeNo.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEyeNo.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEyeNo.IconSize = 25;
            this.btnEyeNo.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.btnEyeNo.IdleBorderRadius = 1;
            this.btnEyeNo.IdleBorderThickness = 1;
            this.btnEyeNo.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.btnEyeNo.IdleIconLeftImage = null;
            this.btnEyeNo.IdleIconRightImage = null;
            this.btnEyeNo.IndicateFocus = false;
            this.btnEyeNo.Location = new System.Drawing.Point(270, 316);
            this.btnEyeNo.Name = "btnEyeNo";
            this.btnEyeNo.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEyeNo.OnDisabledState.BorderRadius = 1;
            this.btnEyeNo.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEyeNo.OnDisabledState.BorderThickness = 1;
            this.btnEyeNo.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEyeNo.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEyeNo.OnDisabledState.IconLeftImage = null;
            this.btnEyeNo.OnDisabledState.IconRightImage = null;
            this.btnEyeNo.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.btnEyeNo.onHoverState.BorderRadius = 1;
            this.btnEyeNo.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEyeNo.onHoverState.BorderThickness = 1;
            this.btnEyeNo.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.btnEyeNo.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(255)))), ((int)(((byte)(175)))));
            this.btnEyeNo.onHoverState.IconLeftImage = null;
            this.btnEyeNo.onHoverState.IconRightImage = null;
            this.btnEyeNo.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.btnEyeNo.OnIdleState.BorderRadius = 1;
            this.btnEyeNo.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEyeNo.OnIdleState.BorderThickness = 1;
            this.btnEyeNo.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.btnEyeNo.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnEyeNo.OnIdleState.IconLeftImage = null;
            this.btnEyeNo.OnIdleState.IconRightImage = null;
            this.btnEyeNo.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.btnEyeNo.OnPressedState.BorderRadius = 1;
            this.btnEyeNo.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEyeNo.OnPressedState.BorderThickness = 1;
            this.btnEyeNo.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(43)))));
            this.btnEyeNo.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(255)))), ((int)(((byte)(175)))));
            this.btnEyeNo.OnPressedState.IconLeftImage = null;
            this.btnEyeNo.OnPressedState.IconRightImage = null;
            this.btnEyeNo.Size = new System.Drawing.Size(18, 23);
            this.btnEyeNo.TabIndex = 71;
            this.btnEyeNo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEyeNo.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEyeNo.TextMarginLeft = 0;
            this.btnEyeNo.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnEyeNo.UseDefaultRadiusAndThickness = true;
            // 
            // btnSubmit
            // 
            this.btnSubmit.AllowAnimations = true;
            this.btnSubmit.AllowMouseEffects = true;
            this.btnSubmit.AllowToggling = false;
            this.btnSubmit.AnimationSpeed = 200;
            this.btnSubmit.AutoGenerateColors = false;
            this.btnSubmit.AutoRoundBorders = false;
            this.btnSubmit.AutoSizeLeftIcon = true;
            this.btnSubmit.AutoSizeRightIcon = true;
            this.btnSubmit.BackColor = System.Drawing.Color.Transparent;
            this.btnSubmit.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(18)))), ((int)(((byte)(18)))));
            this.btnSubmit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSubmit.BackgroundImage")));
            this.btnSubmit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSubmit.ButtonText = "Salvar";
            this.btnSubmit.ButtonTextMarginLeft = 0;
            this.btnSubmit.ColorContrastOnClick = 45;
            this.btnSubmit.ColorContrastOnHover = 45;
            this.btnSubmit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnSubmit.CustomizableEdges = borderEdges3;
            this.btnSubmit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSubmit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSubmit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSubmit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSubmit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSubmit.Font = new System.Drawing.Font("Rubik", 9F, System.Drawing.FontStyle.Bold);
            this.btnSubmit.ForeColor = System.Drawing.Color.White;
            this.btnSubmit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSubmit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSubmit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSubmit.IconMarginLeft = 11;
            this.btnSubmit.IconPadding = 10;
            this.btnSubmit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSubmit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSubmit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSubmit.IconSize = 25;
            this.btnSubmit.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(220)))), ((int)(((byte)(161)))));
            this.btnSubmit.IdleBorderRadius = 9;
            this.btnSubmit.IdleBorderThickness = 1;
            this.btnSubmit.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(18)))), ((int)(((byte)(18)))));
            this.btnSubmit.IdleIconLeftImage = null;
            this.btnSubmit.IdleIconRightImage = null;
            this.btnSubmit.IndicateFocus = false;
            this.btnSubmit.Location = new System.Drawing.Point(37, 362);
            this.btnSubmit.Name = "btnSubmit";
            this.btnSubmit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSubmit.OnDisabledState.BorderRadius = 9;
            this.btnSubmit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSubmit.OnDisabledState.BorderThickness = 1;
            this.btnSubmit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSubmit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSubmit.OnDisabledState.IconLeftImage = null;
            this.btnSubmit.OnDisabledState.IconRightImage = null;
            this.btnSubmit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(221)))), ((int)(((byte)(154)))));
            this.btnSubmit.onHoverState.BorderRadius = 9;
            this.btnSubmit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSubmit.onHoverState.BorderThickness = 1;
            this.btnSubmit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(221)))), ((int)(((byte)(154)))));
            this.btnSubmit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSubmit.onHoverState.IconLeftImage = null;
            this.btnSubmit.onHoverState.IconRightImage = null;
            this.btnSubmit.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(220)))), ((int)(((byte)(161)))));
            this.btnSubmit.OnIdleState.BorderRadius = 9;
            this.btnSubmit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSubmit.OnIdleState.BorderThickness = 1;
            this.btnSubmit.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(18)))), ((int)(((byte)(18)))));
            this.btnSubmit.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSubmit.OnIdleState.IconLeftImage = null;
            this.btnSubmit.OnIdleState.IconRightImage = null;
            this.btnSubmit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(255)))), ((int)(((byte)(175)))));
            this.btnSubmit.OnPressedState.BorderRadius = 9;
            this.btnSubmit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSubmit.OnPressedState.BorderThickness = 1;
            this.btnSubmit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(255)))), ((int)(((byte)(175)))));
            this.btnSubmit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSubmit.OnPressedState.IconLeftImage = null;
            this.btnSubmit.OnPressedState.IconRightImage = null;
            this.btnSubmit.Size = new System.Drawing.Size(137, 29);
            this.btnSubmit.TabIndex = 72;
            this.btnSubmit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSubmit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSubmit.TextMarginLeft = 0;
            this.btnSubmit.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSubmit.UseDefaultRadiusAndThickness = true;
            this.btnSubmit.Click += new System.EventHandler(this.btnSubmit_Click);
            // 
            // btnAlter
            // 
            this.btnAlter.AllowAnimations = true;
            this.btnAlter.AllowMouseEffects = true;
            this.btnAlter.AllowToggling = false;
            this.btnAlter.AnimationSpeed = 200;
            this.btnAlter.AutoGenerateColors = false;
            this.btnAlter.AutoRoundBorders = false;
            this.btnAlter.AutoSizeLeftIcon = true;
            this.btnAlter.AutoSizeRightIcon = true;
            this.btnAlter.BackColor = System.Drawing.Color.Transparent;
            this.btnAlter.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(18)))), ((int)(((byte)(18)))));
            this.btnAlter.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAlter.BackgroundImage")));
            this.btnAlter.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAlter.ButtonText = "Alterar";
            this.btnAlter.ButtonTextMarginLeft = 0;
            this.btnAlter.ColorContrastOnClick = 45;
            this.btnAlter.ColorContrastOnHover = 45;
            this.btnAlter.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnAlter.CustomizableEdges = borderEdges2;
            this.btnAlter.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAlter.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAlter.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAlter.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAlter.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAlter.Font = new System.Drawing.Font("Rubik", 9F, System.Drawing.FontStyle.Bold);
            this.btnAlter.ForeColor = System.Drawing.Color.White;
            this.btnAlter.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAlter.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAlter.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAlter.IconMarginLeft = 11;
            this.btnAlter.IconPadding = 10;
            this.btnAlter.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAlter.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAlter.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAlter.IconSize = 25;
            this.btnAlter.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(220)))), ((int)(((byte)(161)))));
            this.btnAlter.IdleBorderRadius = 9;
            this.btnAlter.IdleBorderThickness = 1;
            this.btnAlter.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(18)))), ((int)(((byte)(18)))));
            this.btnAlter.IdleIconLeftImage = null;
            this.btnAlter.IdleIconRightImage = null;
            this.btnAlter.IndicateFocus = false;
            this.btnAlter.Location = new System.Drawing.Point(180, 362);
            this.btnAlter.Name = "btnAlter";
            this.btnAlter.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAlter.OnDisabledState.BorderRadius = 9;
            this.btnAlter.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAlter.OnDisabledState.BorderThickness = 1;
            this.btnAlter.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAlter.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAlter.OnDisabledState.IconLeftImage = null;
            this.btnAlter.OnDisabledState.IconRightImage = null;
            this.btnAlter.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(221)))), ((int)(((byte)(154)))));
            this.btnAlter.onHoverState.BorderRadius = 9;
            this.btnAlter.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAlter.onHoverState.BorderThickness = 1;
            this.btnAlter.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(221)))), ((int)(((byte)(154)))));
            this.btnAlter.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAlter.onHoverState.IconLeftImage = null;
            this.btnAlter.onHoverState.IconRightImage = null;
            this.btnAlter.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(220)))), ((int)(((byte)(161)))));
            this.btnAlter.OnIdleState.BorderRadius = 9;
            this.btnAlter.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAlter.OnIdleState.BorderThickness = 1;
            this.btnAlter.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(18)))), ((int)(((byte)(18)))));
            this.btnAlter.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAlter.OnIdleState.IconLeftImage = null;
            this.btnAlter.OnIdleState.IconRightImage = null;
            this.btnAlter.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(255)))), ((int)(((byte)(175)))));
            this.btnAlter.OnPressedState.BorderRadius = 9;
            this.btnAlter.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAlter.OnPressedState.BorderThickness = 1;
            this.btnAlter.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(255)))), ((int)(((byte)(175)))));
            this.btnAlter.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAlter.OnPressedState.IconLeftImage = null;
            this.btnAlter.OnPressedState.IconRightImage = null;
            this.btnAlter.Size = new System.Drawing.Size(137, 29);
            this.btnAlter.TabIndex = 73;
            this.btnAlter.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAlter.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAlter.TextMarginLeft = 0;
            this.btnAlter.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAlter.UseDefaultRadiusAndThickness = true;
            this.btnAlter.Click += new System.EventHandler(this.btnAlter_Click);
            // 
            // btnRefresh
            // 
            this.btnRefresh.AllowAnimations = true;
            this.btnRefresh.AllowMouseEffects = true;
            this.btnRefresh.AllowToggling = false;
            this.btnRefresh.AnimationSpeed = 200;
            this.btnRefresh.AutoGenerateColors = false;
            this.btnRefresh.AutoRoundBorders = false;
            this.btnRefresh.AutoSizeLeftIcon = true;
            this.btnRefresh.AutoSizeRightIcon = true;
            this.btnRefresh.BackColor = System.Drawing.Color.Transparent;
            this.btnRefresh.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(18)))), ((int)(((byte)(18)))));
            this.btnRefresh.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnRefresh.BackgroundImage")));
            this.btnRefresh.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.ButtonText = "redo";
            this.btnRefresh.ButtonTextMarginLeft = 0;
            this.btnRefresh.ColorContrastOnClick = 45;
            this.btnRefresh.ColorContrastOnHover = 45;
            this.btnRefresh.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnRefresh.CustomizableEdges = borderEdges1;
            this.btnRefresh.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnRefresh.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRefresh.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRefresh.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRefresh.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnRefresh.Font = new System.Drawing.Font("Font Awesome 5 Pro Light", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnRefresh.ForeColor = System.Drawing.Color.White;
            this.btnRefresh.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRefresh.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnRefresh.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnRefresh.IconMarginLeft = 11;
            this.btnRefresh.IconPadding = 10;
            this.btnRefresh.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnRefresh.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnRefresh.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnRefresh.IconSize = 25;
            this.btnRefresh.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(18)))), ((int)(((byte)(18)))));
            this.btnRefresh.IdleBorderRadius = 1;
            this.btnRefresh.IdleBorderThickness = 1;
            this.btnRefresh.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(18)))), ((int)(((byte)(18)))));
            this.btnRefresh.IdleIconLeftImage = null;
            this.btnRefresh.IdleIconRightImage = null;
            this.btnRefresh.IndicateFocus = false;
            this.btnRefresh.Location = new System.Drawing.Point(326, 320);
            this.btnRefresh.Name = "btnRefresh";
            this.btnRefresh.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRefresh.OnDisabledState.BorderRadius = 1;
            this.btnRefresh.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.OnDisabledState.BorderThickness = 1;
            this.btnRefresh.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRefresh.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRefresh.OnDisabledState.IconLeftImage = null;
            this.btnRefresh.OnDisabledState.IconRightImage = null;
            this.btnRefresh.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(18)))), ((int)(((byte)(18)))));
            this.btnRefresh.onHoverState.BorderRadius = 1;
            this.btnRefresh.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.onHoverState.BorderThickness = 1;
            this.btnRefresh.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(18)))), ((int)(((byte)(18)))));
            this.btnRefresh.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(255)))), ((int)(((byte)(175)))));
            this.btnRefresh.onHoverState.IconLeftImage = null;
            this.btnRefresh.onHoverState.IconRightImage = null;
            this.btnRefresh.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(18)))), ((int)(((byte)(18)))));
            this.btnRefresh.OnIdleState.BorderRadius = 1;
            this.btnRefresh.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.OnIdleState.BorderThickness = 1;
            this.btnRefresh.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(18)))), ((int)(((byte)(18)))));
            this.btnRefresh.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnRefresh.OnIdleState.IconLeftImage = null;
            this.btnRefresh.OnIdleState.IconRightImage = null;
            this.btnRefresh.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(18)))), ((int)(((byte)(18)))));
            this.btnRefresh.OnPressedState.BorderRadius = 1;
            this.btnRefresh.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.OnPressedState.BorderThickness = 1;
            this.btnRefresh.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(18)))), ((int)(((byte)(18)))));
            this.btnRefresh.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(255)))), ((int)(((byte)(175)))));
            this.btnRefresh.OnPressedState.IconLeftImage = null;
            this.btnRefresh.OnPressedState.IconRightImage = null;
            this.btnRefresh.Size = new System.Drawing.Size(19, 17);
            this.btnRefresh.TabIndex = 74;
            this.btnRefresh.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnRefresh.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnRefresh.TextMarginLeft = 0;
            this.btnRefresh.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnRefresh.UseDefaultRadiusAndThickness = true;
            this.btnRefresh.Click += new System.EventHandler(this.btnRefresh_Click);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Rubik", 15F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(93, 16);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(188, 25);
            this.bunifuLabel1.TabIndex = 75;
            this.bunifuLabel1.Text = "Cadastrar Clientes";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuSeparator1
            // 
            this.bunifuSeparator1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator1.BackgroundImage")));
            this.bunifuSeparator1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator1.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator1.LineColor = System.Drawing.Color.Silver;
            this.bunifuSeparator1.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator1.LineThickness = 1;
            this.bunifuSeparator1.Location = new System.Drawing.Point(-2, 50);
            this.bunifuSeparator1.Name = "bunifuSeparator1";
            this.bunifuSeparator1.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator1.Size = new System.Drawing.Size(374, 10);
            this.bunifuSeparator1.TabIndex = 76;
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 10;
            this.bunifuElipse1.TargetControl = this;
            // 
            // frmCustomer
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(18)))), ((int)(((byte)(18)))));
            this.ClientSize = new System.Drawing.Size(371, 416);
            this.Controls.Add(this.bunifuSeparator1);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.btnRefresh);
            this.Controls.Add(this.btnAlter);
            this.Controls.Add(this.btnSubmit);
            this.Controls.Add(this.btnEyeNo);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.txtEndereco);
            this.Controls.Add(this.txtClienteID);
            this.Controls.Add(this.txtEmail);
            this.Controls.Add(this.txtClienteName);
            this.Controls.Add(this.txtTelefone);
            this.Controls.Add(this.txtTlfSufixo);
            this.Controls.Add(this.cmbGrupo);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmCustomer";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "frmCustomer";
            this.Load += new System.EventHandler(this.frmCustomer_Load);
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.ErrorProvider errorProvider;
        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar;
        private Bunifu.UI.WinForms.BunifuDropdown txtTlfSufixo;
        private Bunifu.UI.WinForms.BunifuTextBox txtClienteID;
        private Bunifu.UI.WinForms.BunifuTextBox txtEmail;
        private Bunifu.UI.WinForms.BunifuTextBox txtClienteName;
        private Bunifu.UI.WinForms.BunifuTextBox txtTelefone;
        private Bunifu.UI.WinForms.BunifuTextBox txtEndereco;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuDropdown cmbGrupo;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnEyeNo;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAlter;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSubmit;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnRefresh;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator1;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
    }
}